import 'controller/create_wallet_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class CreateWalletScreen extends GetWidget<CreateWalletController> {const CreateWalletScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(height: getVerticalSize(83), leadingWidth: getHorizontalSize(43), leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray900, margin: getMargin(left: 19, top: 40, bottom: 19), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_create_wallet".tr, margin: getMargin(left: 35)), styleType: Style.bgFill), body: Container(width: double.maxFinite, padding: getPadding(left: 19, top: 15, right: 19, bottom: 15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(351), margin: getMargin(right: 38), child: Text("msg_create_a_wallet".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 1.38))), Padding(padding: getPadding(top: 32), child: Text("lbl_name".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.nameController, margin: getMargin(top: 9), hintText: "lbl_auto_filled".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1), Padding(padding: getPadding(top: 19), child: Text("lbl_wallet_id".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.autogeneratedvaController, margin: getMargin(top: 15, bottom: 5), hintText: "lbl_auto_generated".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done)])), bottomNavigationBar: CustomElevatedButton(text: "lbl_create_wallet".tr, margin: getMargin(left: 19, right: 19, bottom: 30), onTap: () {onTapCreatewallet();}))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
/// Navigates to the walletScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the walletScreen.
onTapCreatewallet() { Get.toNamed(AppRoutes.walletScreen, ); } 
 }
