import 'controller/success_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class SuccessScreen extends GetWidget<SuccessController> {const SuccessScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(height: getVerticalSize(83), leadingWidth: getHorizontalSize(43), leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray900, margin: getMargin(left: 19, top: 40, bottom: 19), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_checkout".tr, margin: getMargin(left: 35)), styleType: Style.bgFill), body: Container(width: double.maxFinite, padding: getPadding(left: 19, top: 20, right: 19, bottom: 20), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 17, right: 17), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: getSize(24), width: getSize(24)), Padding(padding: getPadding(left: 5, top: 4, bottom: 2), child: Text("lbl_shipping".tr, style: theme.textTheme.titleSmall)), Padding(padding: getPadding(top: 12, bottom: 11), child: SizedBox(width: getHorizontalSize(35), child: Divider(color: appTheme.gray400, indent: getHorizontalSize(15)))), CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: getSize(24), width: getSize(24), margin: getMargin(left: 15)), Padding(padding: getPadding(left: 5, top: 5), child: Text("lbl_payment".tr, style: theme.textTheme.titleSmall)), Padding(padding: getPadding(top: 12, bottom: 11), child: SizedBox(width: getHorizontalSize(35), child: Divider(color: appTheme.gray400, indent: getHorizontalSize(15)))), CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: getSize(24), width: getSize(24), margin: getMargin(left: 15)), Padding(padding: getPadding(left: 5, top: 3, bottom: 3), child: Text("lbl_review".tr, style: theme.textTheme.titleSmall))])), Spacer(), Container(decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: getSize(40), width: getSize(40)), Padding(padding: getPadding(top: 16), child: Text("lbl_successful".tr, style: CustomTextStyles.headlineSmallSemiBold)), Container(width: getHorizontalSize(359), margin: getMargin(left: 14, top: 21, right: 15), child: Text("msg_your_payment_has".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71))), CustomElevatedButton(height: getVerticalSize(52), text: "lbl_go_back_home".tr, margin: getMargin(top: 50), onTap: () {onTapGobackhome();})]))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
/// Navigates to the pharmacyScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the pharmacyScreen.
onTapGobackhome() { Get.toNamed(AppRoutes.pharmacyScreen, ); } 
 }
