import 'controller/create_story_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class CreateStoryScreen extends GetWidget<CreateStoryController> {const CreateStoryScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(height: getVerticalSize(83), leadingWidth: getHorizontalSize(43), leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray900, margin: getMargin(left: 19, top: 40, bottom: 19), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_create_story".tr, margin: getMargin(left: 35, top: 40, bottom: 13)), styleType: Style.bgFill), body: Container(width: double.maxFinite, padding: getPadding(left: 19, top: 14, right: 19, bottom: 14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("lbl_title".tr, style: theme.textTheme.titleMedium), CustomTextFormField(controller: controller.enteroneController, margin: getMargin(top: 10), hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1), Container(margin: getMargin(top: 20), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_story".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.checkmarkController, margin: getMargin(top: 15), hintText: "lbl_enter_text".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done, suffix: Container(margin: getMargin(left: 30, top: 8, right: 8, bottom: 8), child: CustomImageView(svgPath: ImageConstant.imgCheckmark)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(128)), maxLines: 7, contentPadding: getPadding(left: 8, top: 9, right: 8, bottom: 9)), Align(alignment: Alignment.centerRight, child: Padding(padding: getPadding(top: 6), child: Text("lbl_0_1000".tr, style: CustomTextStyles.labelLargeIndigo100_1))), Container(margin: getMargin(top: 22), padding: getPadding(top: 1, bottom: 1), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_photos".tr, style: CustomTextStyles.titleMediumBluegray900_1)), CustomImageView(svgPath: ImageConstant.imgFrame12564, height: getVerticalSize(100), width: getHorizontalSize(384), margin: getMargin(top: 17, bottom: 5))])), bottomNavigationBar: CustomElevatedButton(text: "lbl_publish".tr, margin: getMargin(left: 19, right: 19, bottom: 31), onTap: () {onTapPublish();}))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
/// Navigates to the scwCommunityScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the scwCommunityScreen.
onTapPublish() { Get.toNamed(AppRoutes.scwCommunityScreen, ); } 
 }
