import 'controller/specialty_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class SpecialtyScreen extends GetWidget<SpecialtyController> {const SpecialtyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer.withOpacity(1), body: Container(width: getHorizontalSize(390), padding: getPadding(left: 8, top: 10, right: 8, bottom: 10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Container(padding: getPadding(left: 10, top: 13, right: 10, bottom: 13), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("msg_medical_officers".tr, style: theme.textTheme.bodyMedium)), Container(margin: getMargin(top: 4), padding: getPadding(left: 10, top: 13, right: 10, bottom: 13), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("msg_consultant_pediatrician".tr, style: theme.textTheme.bodyMedium)), Container(margin: getMargin(top: 4), padding: getPadding(left: 10, top: 12, right: 10, bottom: 12), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder20), child: Text("msg_consultant_family".tr, style: theme.textTheme.bodyMedium)), CustomElevatedButton(height: getVerticalSize(44), text: "msg_consultant_haematologist".tr, margin: getMargin(top: 4), buttonStyle: CustomButtonStyles.radiusTL22, buttonTextStyle: theme.textTheme.bodyMedium!, onTap: () {onTapConsultant();})])))); } 
/// Navigates to the bookAppointmentNowOneScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the bookAppointmentNowOneScreen.
onTapConsultant() { Get.toNamed(AppRoutes.bookAppointmentNowOneScreen, ); } 
 }
