import 'controller/view_request_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_circleimage.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_4.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_7.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class ViewRequestScreen extends GetWidget<ViewRequestController> {const ViewRequestScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA70001, appBar: CustomAppBar(height: getVerticalSize(103), leadingWidth: getHorizontalSize(85), leading: AppbarCircleimage(imagePath: ImageConstant.imgEllipse565x65, margin: getMargin(left: 20, bottom: 1)), title: Padding(padding: getPadding(left: 15), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [AppbarSubtitle4(text: "lbl_floyd_miles".tr), AppbarSubtitle7(text: "lbl_30_years_old".tr, margin: getMargin(top: 6, right: 5)), AppbarSubtitle7(text: "lbl_male".tr, margin: getMargin(top: 7, right: 56))]))), body: Container(width: double.maxFinite, padding: getPadding(left: 19, top: 20, right: 19, bottom: 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: getPadding(left: 1, top: 9), child: Text("lbl_date_time".tr, style: CustomTextStyles.titleMediumSemiBold_3)), Padding(padding: getPadding(left: 1, top: 12), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_11th_nov_2022".tr, style: CustomTextStyles.titleSmallBlueA400SemiBold), TextSpan(text: "lbl4".tr, style: CustomTextStyles.titleSmallIndigo100), TextSpan(text: "lbl_10_00_am2".tr, style: CustomTextStyles.titleSmallBlueA400SemiBold)]), textAlign: TextAlign.left)), Padding(padding: getPadding(left: 1, top: 31), child: Text("lbl_note".tr, style: CustomTextStyles.titleMediumSemiBold_3)), Container(width: getHorizontalSize(386), margin: getMargin(left: 1, top: 11), child: Text("msg_lorem_ipsum_dolor6".tr, maxLines: 11, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.50))), CustomElevatedButton(height: getVerticalSize(43), text: "lbl_accept".tr, margin: getMargin(top: 29)), CustomOutlinedButton(text: "lbl_reject".tr, margin: getMargin(top: 20), onTap: () {onTapReject();})])))); } 
/// Navigates to the rejectAppointmentScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the rejectAppointmentScreen.
onTapReject() { Get.toNamed(AppRoutes.rejectAppointmentScreen, ); } 
 }
