import 'controller/track_order_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class TrackOrderScreen extends GetWidget<TrackOrderController> {const TrackOrderScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomElevatedButton(height: getVerticalSize(83), text: "lbl_track_order".tr, leftIcon: Container(margin: getMargin(right: 30), child: CustomImageView(svgPath: ImageConstant.imgArrowleftGray900)), buttonStyle: CustomButtonStyles.fillPrimaryContainer1, buttonTextStyle: theme.textTheme.headlineSmall!, onTap: () {onTapTrackorder();}), Padding(padding: getPadding(left: 19, top: 20, right: 19), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("lbl_7788166523".tr, style: CustomTextStyles.titleMediumSemiBold_3), Padding(padding: getPadding(top: 6), child: Text("msg_23_10_2022_9_00".tr, style: theme.textTheme.bodyMedium))]), CustomElevatedButton(height: getVerticalSize(34), width: getHorizontalSize(111), text: "lbl_in_progress".tr, margin: getMargin(top: 3, bottom: 4), buttonStyle: CustomButtonStyles.fillBlueA, buttonTextStyle: CustomTextStyles.titleSmallBlueA400)])), Padding(padding: getPadding(left: 19, top: 38, right: 28, bottom: 5), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgFrame1000000855, height: getVerticalSize(260), width: getHorizontalSize(24)), Expanded(child: Padding(padding: getPadding(left: 20, top: 3, bottom: 3), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [RichText(text: TextSpan(children: [TextSpan(text: "lbl_order_placed".tr, style: CustomTextStyles.titleSmallOnError), TextSpan(text: "msg_your_order_has_been2".tr, style: CustomTextStyles.titleSmallBluegray900_1)]), textAlign: TextAlign.left), Container(width: getHorizontalSize(336), margin: getMargin(top: 34), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_in_progress2".tr, style: CustomTextStyles.titleSmallOnError), TextSpan(text: "msg_your_order_has_been3".tr, style: CustomTextStyles.titleSmallBluegray900_1)]), textAlign: TextAlign.left)), Container(width: getHorizontalSize(306), margin: getMargin(top: 26, right: 30), child: Text("msg_shipped_your_order".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallOnError_1)), Padding(padding: getPadding(top: 29), child: Text("msg_out_for_delivery".tr, style: CustomTextStyles.bodyMediumGray400)), Padding(padding: getPadding(top: 40), child: Text("msg_delivered_your".tr, style: CustomTextStyles.bodyMediumGray400))])))]))])))); } 
/// Navigates to the orderDetailsOneScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the orderDetailsOneScreen.
onTapTrackorder() { Get.toNamed(AppRoutes.orderDetailsOneScreen, ); } 
 }
