import 'controller/reset_password_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class ResetPasswordScreen extends GetWidget<ResetPasswordController> {const ResetPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(leadingWidth: getHorizontalSize(43), leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 19, top: 16, bottom: 15), onTap: () {onTapArrowleftone();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_reset_password".tr)), body: Container(width: double.maxFinite, padding: getPadding(left: 15, top: 22, right: 15, bottom: 22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 4), child: Text("msg_please_reset_your".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(left: 4, top: 33), child: Text("lbl_password".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.passwordController, margin: getMargin(left: 4, top: 10), hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, suffix: Container(margin: getMargin(left: 12, top: 9, right: 13, bottom: 9), decoration: BoxDecoration(borderRadius: BorderRadius.circular(getHorizontalSize(4))), child: CustomImageView(svgPath: ImageConstant.imgIcon)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(42)), contentPadding: getPadding(left: 20, top: 12, bottom: 12)), Padding(padding: getPadding(left: 4, top: 19), child: Text("msg_confirm_password".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.confirmpasswordController, margin: getMargin(left: 4, top: 10), hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done, suffix: Container(margin: getMargin(left: 12, top: 9, right: 13, bottom: 9), decoration: BoxDecoration(borderRadius: BorderRadius.circular(getHorizontalSize(4))), child: CustomImageView(svgPath: ImageConstant.imgIcon)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(42)), contentPadding: getPadding(left: 20, top: 12, bottom: 12)), CustomElevatedButton(text: "lbl_submit".tr, margin: getMargin(left: 4, top: 75)), Align(alignment: Alignment.center, child: Padding(padding: getPadding(top: 25, bottom: 5), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgArrowleftGray900, height: getSize(20), width: getSize(20)), Padding(padding: getPadding(left: 10, top: 3), child: Text("lbl_back_to_sign_in".tr, style: CustomTextStyles.bodySmallGray900_1))])))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
