import 'controller/reschedule_appointment_one_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image_1.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_3.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class RescheduleAppointmentOneScreen extends GetWidget<RescheduleAppointmentOneController> {const RescheduleAppointmentOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer.withOpacity(1), appBar: CustomAppBar(title: AppbarSubtitle3(text: "msg_reschedule_appointment".tr, margin: getMargin(left: 20)), actions: [AppbarImage1(svgPath: ImageConstant.imgEvacloseoutlineBlack900, margin: getMargin(left: 20, top: 16, right: 20, bottom: 16))]), body: Container(width: double.maxFinite, padding: getPadding(left: 18, top: 11, right: 18, bottom: 11), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(351), margin: getMargin(left: 2, right: 38), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_this_appointment2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "msg_september_12_2022".tr, style: CustomTextStyles.titleSmallBlueA400_1)]), textAlign: TextAlign.left)), CustomElevatedButton(height: getVerticalSize(43), text: "lbl_yes".tr, margin: getMargin(left: 2, top: 22), onTap: () {onTapYes();}), CustomOutlinedButton(text: "lbl_no".tr, margin: getMargin(left: 2, top: 20, bottom: 8), buttonStyle: CustomButtonStyles.outlinePrimaryTL10)])))); } 
/// Navigates to the rescheduleAppointmentScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the rescheduleAppointmentScreen.
onTapYes() { Get.toNamed(AppRoutes.rescheduleAppointmentScreen, ); } 
 }
