import 'package:medtech/core/app_export.dart';import 'package:medtech/presentation/create_wallet_screen/models/create_wallet_model.dart';import 'package:flutter/material.dart';/// A controller class for the CreateWalletScreen.
///
/// This class manages the state of the CreateWalletScreen, including the
/// current createWalletModelObj
class CreateWalletController extends GetxController {TextEditingController nameController = TextEditingController();

TextEditingController autogeneratedvaController = TextEditingController();

Rx<CreateWalletModel> createWalletModelObj = CreateWalletModel().obs;

@override void onClose() { super.onClose(); nameController.dispose(); autogeneratedvaController.dispose(); } 
 }
