import 'controller/security_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/custom_checkbox_button.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_icon_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class SecurityScreen extends GetWidget<SecurityController> {const SecurityScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomElevatedButton(height: getVerticalSize(83), text: "lbl_security".tr, leftIcon: Container(margin: getMargin(right: 30), child: CustomImageView(svgPath: ImageConstant.imgArrowleftGray900)), buttonStyle: CustomButtonStyles.fillPrimaryContainer1, buttonTextStyle: theme.textTheme.headlineSmall!, onTap: () {onTapSecurity();}), Padding(padding: getPadding(left: 19, top: 21, right: 19), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 1), child: Text("lbl_password".tr, style: CustomTextStyles.titleMedium18)), CustomIconButton(height: getSize(24), width: getSize(24), padding: getPadding(all: 7), child: CustomImageView(svgPath: ImageConstant.imgIconGray900))])), Padding(padding: getPadding(top: 25), child: Divider(indent: getHorizontalSize(19), endIndent: getHorizontalSize(19))), Padding(padding: getPadding(left: 19, top: 24, right: 19), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 1), child: Text("msg_two_factor_authentication".tr, style: CustomTextStyles.titleMedium18)), CustomIconButton(height: getSize(24), width: getSize(24), padding: getPadding(all: 7), child: CustomImageView(svgPath: ImageConstant.imgIconGray900))])), Padding(padding: getPadding(top: 25), child: Divider(indent: getHorizontalSize(19), endIndent: getHorizontalSize(19))), Padding(padding: getPadding(left: 19, top: 24, right: 19), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 1), child: Text("msg_deactivate_account".tr, style: CustomTextStyles.titleMedium18)), CustomIconButton(height: getSize(24), width: getSize(24), padding: getPadding(all: 7), child: CustomImageView(svgPath: ImageConstant.imgIconGray900))])), Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(left: 19, top: 30), child: Text("msg_are_you_sure_you".tr, style: theme.textTheme.bodyMedium))), Align(alignment: Alignment.centerLeft, child: Container(width: getHorizontalSize(338), margin: getMargin(left: 19, top: 20, right: 70), child: Text("msg_doing_this_will".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71)))), Align(alignment: Alignment.centerLeft, child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_i_understand_the".tr, isExpandedText: true, value: controller.user.value, margin: getMargin(left: 19, top: 15, right: 71), onChange: (value) {controller.user.value = value;}))), CustomOutlinedButton(width: getHorizontalSize(115), text: "lbl_confirm".tr, margin: getMargin(left: 19, top: 25, bottom: 5), alignment: Alignment.centerLeft)])))); } 
/// Navigates to the accountSettingsOneScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the accountSettingsOneScreen.
onTapSecurity() { Get.toNamed(AppRoutes.accountSettingsOneScreen, ); } 
 }
