import 'controller/appointment_rescheduled_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class AppointmentRescheduledScreen extends GetWidget<AppointmentRescheduledController> {const AppointmentRescheduledScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer.withOpacity(1), body: Container(width: double.maxFinite, padding: getPadding(left: 35, top: 20, right: 35, bottom: 20), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgArrowdown, height: getSize(100), width: getSize(100)), Padding(padding: getPadding(top: 18), child: Text("lbl_thank_you".tr, style: CustomTextStyles.titleLargeBlueA400)), Padding(padding: getPadding(top: 20), child: Text("msg_appointment_rescheduled".tr, style: CustomTextStyles.titleLargeMedium)), Container(width: getHorizontalSize(356), margin: getMargin(top: 20), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_you_rescheduled2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "msg_december_12_2022".tr, style: theme.textTheme.bodyMedium!.copyWith(decoration: TextDecoration.lineThrough)), TextSpan(text: "lbl_to2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "msg_december_25_2022".tr, style: CustomTextStyles.titleSmallBlueA400_1)]), textAlign: TextAlign.center))])), bottomNavigationBar: CustomElevatedButton(height: getVerticalSize(43), text: "lbl_done".tr, margin: getMargin(left: 19, right: 19, bottom: 20), onTap: () {onTapDone();}))); } 
/// Navigates to the appointmentsScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the appointmentsScreen.
onTapDone() { Get.toNamed(AppRoutes.appointmentsScreen, ); } 
 }
